#!/bin/bash

docker run --rm --network=host -v $(pwd):/usr/src/app/ -v $HOME/.cargo/git:/usr/local/cargo/git -v $HOME/.cargo/registry:/usr/local/cargo/registry gianlu33/reactive-tools reactive-tools $@
